title: David Kersey
description: Data Science Professional<br><br>
[LinkedIn](https://www.linkedin.com/in/davidrkersey/)
logo: "/pictures/smaller.PNG"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
