title: David Kersey
description: Data Science Professional
<br><br>
   <a href="https://www.linkedin.com/in/davidrkersey/">LinkedIn</a> 
logo: "/pictures/smaller.PNG"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
